post http://localhost:5500/login/
Content-Type: application/json


# {
#     "task": "I have updated the todo.",
#     "priority": "Medium",
#     "completed":false
# }

{
    "username": "Samuel",
    "password": "$2a$10$74435lbBaShQkGhJGS0ADe2XqpDc5a.AWd4Xxqf69EzhWfGpFnCTS"
}

# {
#     "task": "This is new Updated todo",
#     "priority": "High",
#     "completed":true
# }
